/*
This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means.
*/
/*------------------------------------------------------------------------
    File        : DialogResultEnum
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : Mike Fechner / Consultingwerk Ltd.
    Created     : Sat Oct 05 12:04:19 CEST 2019
    Notes       : 
  ----------------------------------------------------------------------*/

ENUM 4GlFanatics.UI.DialogResultEnum :  

    DEFINE ENUM OK 
                Cancel 
                Waiting .

END ENUM.
