/*
This is free and unencumbered software released into the public domain.

Anyone is free to copy, modify, publish, use, compile, sell, or
distribute this software, either in source code form or as a compiled
binary, for any purpose, commercial or non-commercial, and by any
means.
*/
/*------------------------------------------------------------------------
    File        : IInputValidator
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : pjudge
    Created     : Thu Oct 03 09:08:28 EDT 2019
    Notes       : 
  ----------------------------------------------------------------------*/
interface 4GlFanatics.UI.IInputValidator:  

end interface.